Backend development
mikenester/corrieri-nester-portfolio pull request #2
Opened 2021-07-20 15:22 UTC by CyberDragonWizard

2021-07-20 18:19 UTC, mcorrieri approved these changes
Mongo db backend?

2021-07-20 18:32 UTC, mikenester requested changes
Add a .gitignore file and ignore the `node_modules `directory and the `.env` file. `.env` should never be in source control because it will usually contain secrets, like API Keys.
https://www.atlassian.com/git/tutorials/saving-changes/gitignore

2021-07-21 22:17 UTC, mikenester commented on backend/.gitignore
> +node_modules/
this didn't work

2021-07-21 22:20 UTC, mikenester commented on backend/.gitignore
> +node_modules/
delete this file

2021-07-21 22:20 UTC, CyberDragonWizard commented on backend/.gitignore
> +node_modules/
Ill try again

2021-07-21 23:24 UTC, mikenester commented on backend/routes/Post.js
> +        res.status(500).json({success: false})
500 is an internal server error. this should be 400. You never want to intentionally throw a 500. Is the app crashes, it auto throws 500

2021-07-21 23:24 UTC, mikenester approved these changes

2021-07-24 15:33 UTC, merged